name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag elibonanni/web_server
    - name: Push the image to DockerHub
      run: docker login -u elibonanni -p ${{ secrets.DOCKER_TOKEN }} && docker push elibonanni/web_server
